workflows:
  android-workflow:
    name: Boombapdap Android Build
    # Убираем явное указание linux, по умолчанию на фри-тире часто доступны Mac mini
    instance_type: mac_mini_m1 
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Install Rust and Tools
        script: |
          # Установка Rust
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup target add aarch64-linux-android
          
          # Установка генератора моста
          cargo install flutter_rust_bridge_codegen --version 2.0.0
          
          # Генерация моста
          chmod +x generate_bridge.sh
          ./generate_bridge.sh
      - name: Build Android APK
        script: |
          cd app_flutter
          flutter pub get
          flutter build apk --release --target-platform android-arm64
    artifacts:
      - app_flutter/build/app/outputs/flutter-apk/*.apk
