[package]
name = "rust_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
flutter_rust_bridge = "2.0.0"
anyhow = "1.0"
lazy_static = "1.4"
parking_lot = "0.12"
hound = "3.5"
rubato = "0.15"
rodio = "0.17"
# Добавьте необходимые зависимости, например, для обработки аудио
# rodio = "0.17"
# hound = "3.5"
